---
apiVersion: v1
kind: Service
metadata:
  name: smail
  namespace: smail
  labels:
    app: smail
spec:
  type: ClusterIP
  selector:
    app: smail
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http